/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Artwork = {
  _id: string;
  _type: "artwork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  year?: number;
  description?: string;
  technique?: string;
  dimensions?: {
    width?: number;
    height?: number;
    depth?: number;
    unit?: "cm";
  };
  mainImage: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  status: "available" | "reserved" | "sold" | "exhibition";
  commerce?: {
    saleId?: string;
    paymentPreferenceId?: string;
    providerPaymentId?: string;
    reservationExpiresAt?: string;
    updatedAt?: string;
  };
  salePosition?: number;
  featured?: boolean;
  catalogNumber?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Artwork
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/artwork.ts
// Variable: ARTWORKS_QUERY
// Query: *[    _type == "artwork" &&    status in $statuses &&    defined(slug.current) &&    defined(mainImage.asset._ref)  ]    | order(year desc, _updatedAt desc, _id asc) {    "id": _id,    title,    "slug": slug.current,    year,    description,    technique,    dimensions,    "image": mainImage {      asset,      crop,      hotspot,      alt    },    status,    featured,    catalogNumber  }
export type ARTWORKS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  slug: string;
  year: number | null;
  description: string | null;
  technique: string | null;
  dimensions: {
    width?: number;
    height?: number;
    depth?: number;
    unit?: "cm";
  } | null;
  image: {
    asset: SanityImageAssetReference;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
  };
  status: "available" | "exhibition" | "reserved" | "sold";
  featured: boolean | null;
  catalogNumber: string | null;
}>;

// Source: src/sanity/queries/artwork.ts
// Variable: SALE_ARTWORKS_QUERY
// Query: *[    _type == "artwork" &&    status in ["available", "reserved"] &&    defined(slug.current) &&    defined(mainImage.asset._ref)  ]    | order(        defined(salePosition) desc,        salePosition asc,        year desc,        _updatedAt desc,        _id asc      ) {    "id": _id,    title,    "slug": slug.current,    year,    description,    technique,    dimensions,    "image": mainImage {      asset,      crop,      hotspot,      alt    },    status,    featured,    catalogNumber  }
export type SALE_ARTWORKS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  slug: string;
  year: number | null;
  description: string | null;
  technique: string | null;
  dimensions: {
    width?: number;
    height?: number;
    depth?: number;
    unit?: "cm";
  } | null;
  image: {
    asset: SanityImageAssetReference;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
  };
  status: "available" | "exhibition" | "reserved" | "sold";
  featured: boolean | null;
  catalogNumber: string | null;
}>;

// Source: src/sanity/queries/artwork.ts
// Variable: ARTWORK_QUERY
// Query: *[    _type == "artwork" &&    slug.current == $slug &&    defined(mainImage.asset._ref)  ][0] {    "id": _id,    _updatedAt,    title,    "slug": slug.current,    year,    description,    technique,    dimensions,    "image": mainImage {      asset,      crop,      hotspot,      alt    },    "images": images[defined(asset._ref)] {      _key,      asset,      crop,      hotspot,      alt    },    status,    featured,    catalogNumber  }
export type ARTWORK_QUERY_RESULT = {
  id: string;
  _updatedAt: string;
  title: string;
  slug: string;
  year: number | null;
  description: string | null;
  technique: string | null;
  dimensions: {
    width?: number;
    height?: number;
    depth?: number;
    unit?: "cm";
  } | null;
  image: {
    asset: SanityImageAssetReference;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
  };
  images: Array<{
    _key: string;
    asset: SanityImageAssetReference;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string | null;
  }> | null;
  status: "available" | "exhibition" | "reserved" | "sold";
  featured: boolean | null;
  catalogNumber: string | null;
} | null;

// Source: src/sanity/queries/artwork.ts
// Variable: ARTWORK_SLUGS_QUERY
// Query: *[    _type == "artwork" &&    defined(slug.current) &&    defined(mainImage.asset._ref)  ] {    "slug": slug.current  }
export type ARTWORK_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/queries/artwork.ts
// Variable: ARTWORK_SITEMAP_QUERY
// Query: *[    _type == "artwork" &&    defined(slug.current) &&    defined(mainImage.asset._ref)  ]    | order(_updatedAt desc) {    "slug": slug.current,    _updatedAt  }
export type ARTWORK_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: src/sanity/queries/artwork.ts
// Variable: ARTWORK_INTEREST_QUERY
// Query: *[_type == "artwork" && _id == $id && status == "available"][0] {    "id": _id,    title,    status  }
export type ARTWORK_INTEREST_QUERY_RESULT = {
  id: string;
  title: string;
  status: "available" | "exhibition" | "reserved" | "sold";
} | null;

// Source: src/sanity/queries/artwork.ts
// Variable: ARTWORKS_BY_IDS_QUERY
// Query: *[_type == "artwork" && _id in $ids] {    "id": _id,    title,    year,    technique,    dimensions,    status,    catalogNumber  }
export type ARTWORKS_BY_IDS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  year: number | null;
  technique: string | null;
  dimensions: {
    width?: number;
    height?: number;
    depth?: number;
    unit?: "cm";
  } | null;
  status: "available" | "exhibition" | "reserved" | "sold";
  catalogNumber: string | null;
}>;

// Source: src/sanity/queries/artwork.ts
// Variable: ADMIN_SALE_ARTWORKS_QUERY
// Query: *[_type == "artwork" && _id in $ids] {    "id": _id,    title,    "slug": slug.current  }
export type ADMIN_SALE_ARTWORKS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  slug: string;
}>;

// Source: src/sanity/queries/artwork.ts
// Variable: ADMIN_ACTIVITY_ARTWORKS_QUERY
// Query: *[_type == "artwork" && _id in $ids] {    "id": _id,    title  }
export type ADMIN_ACTIVITY_ARTWORKS_QUERY_RESULT = Array<{
  id: string;
  title: string;
}>;

// Source: src/sanity/queries/artwork.ts
// Variable: ARTWORK_COMMERCE_QUERY
// Query: *[    _type == "artwork" &&    _id in $ids  ] {    _id,    _rev,    status,    "slug": slug.current,    commerce {      saleId,      paymentPreferenceId,      providerPaymentId,      reservationExpiresAt,      updatedAt    }  }
export type ARTWORK_COMMERCE_QUERY_RESULT = Array<{
  _id: string;
  _rev: string;
  status: "available" | "exhibition" | "reserved" | "sold";
  slug: string;
  commerce: {
    saleId: string | null;
    paymentPreferenceId: string | null;
    providerPaymentId: string | null;
    reservationExpiresAt: string | null;
    updatedAt: string | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "artwork" &&\n    status in $statuses &&\n    defined(slug.current) &&\n    defined(mainImage.asset._ref)\n  ]\n    | order(year desc, _updatedAt desc, _id asc) {\n    "id": _id,\n    title,\n    "slug": slug.current,\n    year,\n    description,\n    technique,\n    dimensions,\n    "image": mainImage {\n      asset,\n      crop,\n      hotspot,\n      alt\n    },\n    status,\n    featured,\n    catalogNumber\n  }\n': ARTWORKS_QUERY_RESULT;
    '\n  *[\n    _type == "artwork" &&\n    status in ["available", "reserved"] &&\n    defined(slug.current) &&\n    defined(mainImage.asset._ref)\n  ]\n    | order(\n        defined(salePosition) desc,\n        salePosition asc,\n        year desc,\n        _updatedAt desc,\n        _id asc\n      ) {\n    "id": _id,\n    title,\n    "slug": slug.current,\n    year,\n    description,\n    technique,\n    dimensions,\n    "image": mainImage {\n      asset,\n      crop,\n      hotspot,\n      alt\n    },\n    status,\n    featured,\n    catalogNumber\n  }\n': SALE_ARTWORKS_QUERY_RESULT;
    '\n  *[\n    _type == "artwork" &&\n    slug.current == $slug &&\n    defined(mainImage.asset._ref)\n  ][0] {\n    "id": _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    year,\n    description,\n    technique,\n    dimensions,\n    "image": mainImage {\n      asset,\n      crop,\n      hotspot,\n      alt\n    },\n    "images": images[defined(asset._ref)] {\n      _key,\n      asset,\n      crop,\n      hotspot,\n      alt\n    },\n    status,\n    featured,\n    catalogNumber\n  }\n': ARTWORK_QUERY_RESULT;
    '\n  *[\n    _type == "artwork" &&\n    defined(slug.current) &&\n    defined(mainImage.asset._ref)\n  ] {\n    "slug": slug.current\n  }\n': ARTWORK_SLUGS_QUERY_RESULT;
    '\n  *[\n    _type == "artwork" &&\n    defined(slug.current) &&\n    defined(mainImage.asset._ref)\n  ]\n    | order(_updatedAt desc) {\n    "slug": slug.current,\n    _updatedAt\n  }\n': ARTWORK_SITEMAP_QUERY_RESULT;
    '\n  *[_type == "artwork" && _id == $id && status == "available"][0] {\n    "id": _id,\n    title,\n    status\n  }\n': ARTWORK_INTEREST_QUERY_RESULT;
    '\n  *[_type == "artwork" && _id in $ids] {\n    "id": _id,\n    title,\n    year,\n    technique,\n    dimensions,\n    status,\n    catalogNumber\n  }\n': ARTWORKS_BY_IDS_QUERY_RESULT;
    '\n  *[_type == "artwork" && _id in $ids] {\n    "id": _id,\n    title,\n    "slug": slug.current\n  }\n': ADMIN_SALE_ARTWORKS_QUERY_RESULT;
    '\n  *[_type == "artwork" && _id in $ids] {\n    "id": _id,\n    title\n  }\n': ADMIN_ACTIVITY_ARTWORKS_QUERY_RESULT;
    '\n  *[\n    _type == "artwork" &&\n    _id in $ids\n  ] {\n    _id,\n    _rev,\n    status,\n    "slug": slug.current,\n    commerce {\n      saleId,\n      paymentPreferenceId,\n      providerPaymentId,\n      reservationExpiresAt,\n      updatedAt\n    }\n  }\n': ARTWORK_COMMERCE_QUERY_RESULT;
  }
}
